use_frameworks!

platform :ios, '10.0'

target 'ZDLog_Example' do
  pod 'ZDLog', :path => '../'
  pod 'CocoaLumberjack', '~> 3.7.0'
  
  target 'ZDLog_Tests' do
    inherit! :search_paths

    
  end
end
